#模拟器
#platformVersion: 4.4.2
#deviceName: 127.0.0.1:7555

platformName: Android
platformVersion: 6.0
deviceName: 127.0.0.1:6555

appname: kaoyanbang.apk
appPackage: com.tal.kaoyan
appActivity: com.tal.kaoyan.ui.activity.SplashActivity

noReset: False
unicodeKeyboard: True
resetKeyboard: True

ip: 127.0.0.1
port: 4723